### ISSUE TITLE
Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by michelalbers** [enisdenjo/graphql-sse#69]
**Screenshot**
<img width="1062" alt="image" src="https://github.com/enisdenjo/graphql-sse/assets/646691/2522efa1-8047-4c57-a9ab-c7a054e37122">

**Expected Behaviour**
Do not write to the stream after it is closed / destroyed

**Actual Behaviour**
Writes to stream after it was destroyed which results in an error.

**Debug Information**
This bug resulted when using the `use/express` handler created with a ```createHandler``` call. According to the code there is no check in place wether the stream was closed in the meantime.

**Further Information**
Maybe introduce a variable ```let cancelled = false;``` and set it to true once the stream was closed. Check for ```cancelled``` before trying to do a ```.write()```.

**Comment by enisdenjo** [comment]
Hmm, I thought that the `res.once('close', body.return)` above the loop should suffice, but apparently not. 

I am trying to write a failing test now and then I'll proceed with fixing the bug.

Thanks for reporting!

**Comment by enisdenjo** [comment]
@michelalbers any luck with the repro?

**Comment by enisdenjo** [comment]
Unable to reproduce. [Added some tests too.](https://github.com/enisdenjo/graphql-sse/commit/4ff1f9c833fb5b6c3a0355fe1e609236a4194c27)

**Comment by groundmuffin** [comment]
Same error: 
Node version: 16.14.2

`Error: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:371:5)
    at write_ (node:_http_outgoing:750:11)
    at ServerResponse.write (node:_http_outgoing:707:15)
    at /Users/vadim/Projects/graphql-api/node_modules/graphql-sse/lib/use/express.js:75:56
    at new Promise (<anonymous>)
    at handleRequest (/Users/vadim/Projects/graphql-api/node_modules/graphql-sse/lib/use/express.js:75:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/vadim/Projects/graphql-api/src/express.js:162:5 {
  code: 'ERR_STREAM_DESTROYED'
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: Cannot render headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:312:13)
    at ServerResponse.writeHead (/Users/vadim/Projects/graphql-api/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/Users/vadim/Projects/graphql-api/node_modules/on-headers/index.js:44:26)
    at /Users/vadim/Projects/graphql-api/src/express.js:166:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Process finished with exit code 1
`

**Comment by enisdenjo** [comment]
A repro would be very helpful as I am unable to create one myself.

**Comment by enisdenjo** [comment]
The write loop should break as soon as the connection closes (see https://github.com/enisdenjo/graphql-sse/issues/69#issuecomment-1642080038).

This line takes care of it:
https://github.com/enisdenjo/graphql-sse/blob/256b590370f694afc5dbc143a2fcc3a74a41be20/src/use/express.ts#L96

I am suspicious that `express` itself is late in reporting the closed connection event.

**Comment by groundmuffin** [comment]
Lets assume express actually is late in reporting the closed connection event. Isn't that enough reason to check the `res` availability before calling .write on it?

**Comment by groundmuffin** [comment]
Also I suppose that setting a handler on a 'close' event put it on a Macrotask queue, while setting a promise callback put it on a Microtask queue. Because of the fact that Microtask queue is consulted more frequently by design, we can meet a situation when the "for loop" handler is called before the "once" one.

**Comment by groundmuffin** [comment]
It's still happening

```
Error: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:371:5)
    at write_ (node:_http_outgoing:750:11)
    at ServerResponse.write (node:_http_outgoing:707:15)
    at closed (/Users/vadim/Projects/graphql-api/node_modules/graphql-sse/lib/use/express.js:81:25)
    at new Promise (<anonymous>)
    at handleRequest (/Users/vadim/Projects/graphql-api/node_modules/graphql-sse/lib/use/express.js:75:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/vadim/Projects/graphql-api/src/express.js:162:5 {
  code: 'ERR_STREAM_DESTROYED'
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: Cannot render headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:312:13)
    at ServerResponse.writeHead (/Users/vadim/Projects/graphql-api/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/Users/vadim/Projects/graphql-api/node_modules/on-headers/index.js:44:26)
    at /Users/vadim/Projects/graphql-api/src/express.js:166:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by enisdenjo** [comment]
Wow, then the `.closed` flag is wrong too. 🤔

**Comment by enisdenjo** [comment]
@groundmuffin, @michelalbers can you try out [v2.2.3](https://github.com/enisdenjo/graphql-sse/releases/tag/v2.2.3)? I use the `.writable` flag there instead.
